with-expecter: true
outpkg: "{{.PackageName}}_mocks"
packages:
  github.com/support-pl/infinimesh-proto/proto/eventbus:
    interfaces:
      EventsServiceClient:
  github.com/support-pl/infinimesh-proto/eventbus/eventbusconnect:
    interfaces:
      EventsServiceClient:

  github.com/support-pl/infinimesh-proto/handsfree:
    interfaces:
      HandsfreeServiceClient:
  github.com/support-pl/infinimesh-proto/handsfree/handsfreeconnect:
    interfaces:
      HandsfreeServiceClient:

  github.com/support-pl/infinimesh-proto/node:
    interfaces:
      AccountsServiceClient:
      DevicesServiceClient:
      NamespacesServiceClient:
      SessionsServiceClient:
      ShadowServiceClient:
      InternalServiceClient:

  github.com/support-pl/infinimesh-proto/node/nodeconnect:
    interfaces:
      AccountsServiceClient:
      DevicesServiceClient:
      NamespacesServiceClient:
      SessionsServiceClient:
      ShadowServiceClient:
      InternalServiceClient:

  github.com/support-pl/infinimesh-proto/shadow:
    interfaces:
      ShadowServiceClient:
      ShadowService_StreamShadowServer:
  github.com/support-pl/infinimesh-proto/shadow/shadowconnect:
    interfaces:
      ShadowServiceClient:

  github.com/support-pl/infinimesh-proto/plugins:
    interfaces:
      PluginsServiceClient:
  github.com/support-pl/infinimesh-proto/plugins/pluginsconnect:
    interfaces:
      PluginsServiceClient:

  github.com/support-pl/infinimesh-proto/timeseries:
    interfaces:
      TimeseriesServiceClient:
  github.com/support-pl/infinimesh-proto/timeseries/timeseriesconnect:
    interfaces:
      TimeseriesServiceClient:
