//
//Copyright © 2021-2023 Infinite Devices GmbH, Nikita Ivanovski info@slnt-opp.xyz
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: handsfree/handsfree.proto

package handsfree

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HandsfreeService_Send_FullMethodName    = "/infinimesh.handsfree.HandsfreeService/Send"
	HandsfreeService_Connect_FullMethodName = "/infinimesh.handsfree.HandsfreeService/Connect"
)

// HandsfreeServiceClient is the client API for HandsfreeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HandsfreeServiceClient interface {
	Send(ctx context.Context, in *ControlPacket, opts ...grpc.CallOption) (*ControlPacket, error)
	Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlPacket], error)
}

type handsfreeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHandsfreeServiceClient(cc grpc.ClientConnInterface) HandsfreeServiceClient {
	return &handsfreeServiceClient{cc}
}

func (c *handsfreeServiceClient) Send(ctx context.Context, in *ControlPacket, opts ...grpc.CallOption) (*ControlPacket, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlPacket)
	err := c.cc.Invoke(ctx, HandsfreeService_Send_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *handsfreeServiceClient) Connect(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ControlPacket], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HandsfreeService_ServiceDesc.Streams[0], HandsfreeService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectionRequest, ControlPacket]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HandsfreeService_ConnectClient = grpc.ServerStreamingClient[ControlPacket]

// HandsfreeServiceServer is the server API for HandsfreeService service.
// All implementations must embed UnimplementedHandsfreeServiceServer
// for forward compatibility.
type HandsfreeServiceServer interface {
	Send(context.Context, *ControlPacket) (*ControlPacket, error)
	Connect(*ConnectionRequest, grpc.ServerStreamingServer[ControlPacket]) error
	mustEmbedUnimplementedHandsfreeServiceServer()
}

// UnimplementedHandsfreeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHandsfreeServiceServer struct{}

func (UnimplementedHandsfreeServiceServer) Send(context.Context, *ControlPacket) (*ControlPacket, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedHandsfreeServiceServer) Connect(*ConnectionRequest, grpc.ServerStreamingServer[ControlPacket]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHandsfreeServiceServer) mustEmbedUnimplementedHandsfreeServiceServer() {}
func (UnimplementedHandsfreeServiceServer) testEmbeddedByValue()                          {}

// UnsafeHandsfreeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HandsfreeServiceServer will
// result in compilation errors.
type UnsafeHandsfreeServiceServer interface {
	mustEmbedUnimplementedHandsfreeServiceServer()
}

func RegisterHandsfreeServiceServer(s grpc.ServiceRegistrar, srv HandsfreeServiceServer) {
	// If the following call pancis, it indicates UnimplementedHandsfreeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HandsfreeService_ServiceDesc, srv)
}

func _HandsfreeService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlPacket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HandsfreeServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HandsfreeService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HandsfreeServiceServer).Send(ctx, req.(*ControlPacket))
	}
	return interceptor(ctx, in, info, handler)
}

func _HandsfreeService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ConnectionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HandsfreeServiceServer).Connect(m, &grpc.GenericServerStream[ConnectionRequest, ControlPacket]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HandsfreeService_ConnectServer = grpc.ServerStreamingServer[ControlPacket]

// HandsfreeService_ServiceDesc is the grpc.ServiceDesc for HandsfreeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HandsfreeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infinimesh.handsfree.HandsfreeService",
	HandlerType: (*HandsfreeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _HandsfreeService_Send_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HandsfreeService_Connect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "handsfree/handsfree.proto",
}
